import Image from "next/image"
import Links from "../component/Links"
import logo from '../images/footerimage.jpg'
import mainpic from '../images/pic2.png'
import {BsFillPersonFill} from 'react-icons/bs'
import {RiLockPasswordFill} from 'react-icons/ri'

export const metadata = {
  title: 'Sign In',
  description: 'Generated by Moment Icon app',
}

export default function Home() {
  const year = new Date().getFullYear()
  return (
    <main className='py-[70px] px-[20px] md:py-[70px] md:px-[100px]'>
      <div className='bg-slate-300 rounded-3xl flex'>
        <div className='bg-blue-400 space-y-14 py-9 px-8 rounded-3xl text-white md:w-[30vw]'>
          <div className='flex space-x-2 px-7'><Image src={logo} alt='logo' width={30} height={30} className='rounded-full' /> <span>Moment Icon</span></div>
          <Image src={mainpic} alt='mainpic' width={400} height={400} />
          <p className='text-[10px] text-center pt-10'>Copyright &copy; {year}, Moment Icon, All right reserved</p>
        </div>
        <div className='px-10 md:px-48 py-20'>
          <div className='shadow-2xl grid rounded-2xl md:w-[30vw] h-[30vh]'>
            <div className='py-4 px-6 rounded-t-2xl text-[20px]'>
              <Links />
            </div>
            <div className='bg-white rounded-2xl px-10 py-5 md:px-14 md:py-8'>
                <fieldset className='text-blue-400 text-lg grid space-y-5'>
                  <label className='flex gap-3 items-center border border-slate-800 rounded-lg px-2'>
                  <BsFillPersonFill/> <input type="text" placeholder='Email or ID' className='border-l border-l-slate-800 px-2 outline-none text-slate-800' required/>
                  </label> 
                  <label className='flex gap-3 items-center border border-slate-800 rounded-lg px-2'>
                  <RiLockPasswordFill/><input type="text" placeholder='********' className='border-l border-l-slate-800 px-2 outline-none text-slate-800' required/>
                  </label> 
                  <button type="submit" className='border bg-blue-700 py-2 px-9 w-full rounded-lg text-slate-200'>
                    Sign In
                  </button>
                  
                  <p className="text-red-800 text-[12px] text-center">Can&#39;t remember Password?<a className="text-gray-950 hover:text-red-800" href="/resetpassword">Click Here</a></p>
              

                </fieldset>
            </div>
          </div>
        </div>

      </div>
    </main>
  )
}
