import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './component/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sign Up',
  description: 'Generated by Moment Icon app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[url(https://images.unsplash.com/photo-1662130187270-a4d52c700eb6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDIwN3xfaGItZGw0US00VXx8ZW58MHx8fHx8&auto=format&fit=crop&w=800&q=60)] bg-fixed md:bg-cover text-black px-2'>
        {children}
      
      
         <Footer />
      </body>
    </html>
  )
}
