import Link from 'next/link'
import React from 'react'


export const metadata = {
    title: 'Reset Password',
    description: 'Generated by Moment Icon app',
  }

export default function Links() {
  return (
    <div>
        <div>
            <ul>
              <Link href='/resetpassword'>
              <li>click here</li>
              </Link>
            </ul>
        </div>
    </div>
  )
}
